Calculator app built using react- Milestone #3
blackpintz/React-Calculator pull request #3
Opened 2020-12-04 11:21 UTC by blackpintz

## Project Specifics

- Build the calculator function.

- Use `big.js` node package for precise calculations.

2020-12-04 14:31 UTC, mosaaleb requested changes
#### Changes required

Well done @blackpintz :clap:. You have done amazing work so far in this milestone. Yet, the calculate functionality is still incomplete. Check my comments below.

Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

2020-12-04 14:31 UTC, mosaaleb commented on src/logic/calculate.js
> +  if (btn === '+/-') {
- [ ] Well done handling the '+/-' button press, but situations we need to handle here:

- what if the `btn` is `AC` or `=` or `.`, what the object `{total, next, operation}` that you will return would like?

- what if the `btn` is a number? what if the value before is also a number, or an operation? how would handle each case?

- Note that you will using the `operate` method only if the user pressed the `=` button, or pressed any other operation (+, -, ..) while there still an operation. For example if the user typed:
`5 + 6 =` => should fire operate method, the return value should become the `total`.
`5 + 6 +` => should fire operate method, the return value should become the `total`, but the `operation` is set to be `+`

Make sure to handle all possible scenarios.

2020-12-05 18:21 UTC, sumancrest0001 requested changes
**Status: Changes required :gear:
Hello @blackpintz** 
Thank you for implementing the changes requested by the previous TSE. But there are still some changes required. Please consider the following points.
[Required] Consider more edge cases. For example, when we click the **'+'** button do we need to update operation data or not? What happens when we click a number button after evaluating an operation. 
[Required] Please do not change the linter configuration. Make a PR if needed.

**If you need help to make necessary changes then please message me on slack Suman Shrestha. Happy coding!!!**

2020-12-05 18:25 UTC, sumancrest0001 commented on src/logic/operate.js
> +      break;
Consider a scenario when we click the "=" button after 5 + 6 were clicked then what will be the result?

2020-12-07 12:46 UTC, shloch requested changes
## Hello @blackpintz 

Sorry for reviewing late when I claimed more than 10hours ago. i had some trouble on my PC mounting the project. 
More seriously, I have noticed the improvement based on the former reviews. You are progressively polishing the milestones and this is great. I have added on top of that a smaller task to round up with before you get a final thumbs up. This is basically handling the zero-division error (which will come up when you integrate these modules on the final design)

This is the final review hopefully

Happy coding

2020-12-07 12:46 UTC, shloch commented on src/components/App.js
> +  console.log(Calculator({ total: '2', next: '3', operation: '*' }, '+'));
`console.logs` have been asked to be removed for all `javascript` processes, at least on final versions as they downplay performances. Use for debut, then delete when submitting for review.

2020-12-07 12:46 UTC, shloch commented on src/logic/operate.js
> +      break;
Handle division by ZERO errors. If `secondNum` is zero, this will generate an error. You can return `division by zero error` or `Infinity` or something more creative.

Please do this and we'll be fine

2020-12-07 14:22 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello @blackpintz :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-12-07 14:24 UTC, merged